language: go

go:
  - 1.10.x
  - tip

before_install:
  - go get -t -v ./...

script:
  - pwd
  - ls -RalF
  - cd src/github.com/TomSweeneyRedHat/coveragelab
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
